services:
  postgres:
    image: 'postgres:18.4'
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=klab'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=controle-de-produtos-pedidos-db'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - pg_net
  app:
    build: .
    container_name: controle-de-produtos-pedidos
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/controle-de-produtos-pedidos-db'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_DATASOURCE_USERNAME=klab'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    ports:
      - '80:8080'
  pgadmin:
    image: 'dpage/pgadmin4'
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@klab.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pg_net
volumes:
  postgres_data:
  pgadmin_data:

networks:
  pg_net:
    driver: bridge
